data_sources:
  offensive_stats_url: "https://www.pro-football-reference.com/years/2024/"
  defensive_stats_url: "https://www.pro-football-reference.com/years/2024/opp.htm"

calculation_thresholds:
  offensive_threshold: 0.5
  defensive_threshold: 0.5
